workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    scripts:
      - name: Build for iOS Device
        script: | 
          flutter pub get
          # Nastavenie premenných prostredia, ktoré Xcode prečíta pred buildom
          export CODE_SIGNING_ALLOWED=NO
          export CODE_SIGNING_REQUIRED=NO
          export CODE_SIGN_IDENTITY=""
          
          # Build IPA archívu bez extra parametrov, ktoré by mohli miasť Flutter
          flutter build ipa --release --no-codesign --build-number=1 --build-name=1.0.0
    artifacts:
      - build/ios/ipa/*.ipa