workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    scripts:
      - name: Build for iOS Device
        script: | 
          flutter pub get
          flutter clean
          # Tento príkaz povie Flutteru, aby ignoroval Team ID a len vygeneroval kód
          flutter build ios --debug --no-codesign --extra-gen-snapshot-options=--no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app