name: moja_prva_appka
description: "AR aplikacia na vymenu slnka za mesiac."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  geolocator: ^13.0.1
  apsl_sun_calc: ^0.0.4
  motion_sensors: ^0.1.0  # TOTO JE KLÚČ (podľa tvojho obrázku 8193bf)
  cupertino_icons: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true