platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_flutter_install_all_ios_pods file_expand_path(File.join('..', '..', '..', 'flutter', 'packages', 'flutter_tools', 'bin', 'podhelper.rb'), __FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end