platform :ios, '13.0'

# Dynamické načítanie Flutteru bez pevne zadanej cesty
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} not found. If you're on Windows, make sure you ran flutter pub get."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/\AFLUTTER_ROOT=(.*)\z/)
    return matches[1] if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}."
end

load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end